#ifndef QTDEMONRUNTIMERENDERGLOBAL_H
#define QTDEMONRUNTIMERENDERGLOBAL_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

#ifndef QT_STATIC
#  if defined(QT_BUILD_DEMONRUNTIMERENDER_LIB)
#    define Q_DEMONRUNTIMERENDER_EXPORT Q_DECL_EXPORT
#  else
#    define Q_DEMONRUNTIMERENDER_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define Q_DEMONRUNTIMERENDER_EXPORT
#endif

QT_END_NAMESPACE

#endif // QTDEMONRUNTIMERENDERGLOBAL_H
