#ifndef QDEMONRENDERLOGGING_H
#define QDEMONRENDERLOGGING_H

#include <QtDemonRender/qtdemonrenderglobal.h>
#include <QtCore/QLoggingCategory>

QT_BEGIN_NAMESPACE

Q_DECLARE_LOGGING_CATEGORY(GL_ERROR)
Q_DECLARE_LOGGING_CATEGORY(INVALID_PARAMETER)
Q_DECLARE_LOGGING_CATEGORY(INVALID_OPERATION)
Q_DECLARE_LOGGING_CATEGORY(OUT_OF_MEMORY)
Q_DECLARE_LOGGING_CATEGORY(INTERNAL_ERROR)
Q_DECLARE_LOGGING_CATEGORY(PERF_WARNING)
Q_DECLARE_LOGGING_CATEGORY(PERF_INFO)
Q_DECLARE_LOGGING_CATEGORY(TRACE_INFO)
Q_DECLARE_LOGGING_CATEGORY(WARNING)

QT_END_NAMESPACE

#endif // QDEMONRENDERLOGGING_H
