#ifndef QTDEMONRENDERGLOBAL_H
#define QTDEMONRENDERGLOBAL_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

#ifndef QT_STATIC
#if defined(QT_BUILD_DEMONRENDER_LIB)
#define Q_DEMONRENDER_EXPORT Q_DECL_EXPORT
#else
#define Q_DEMONRENDER_EXPORT Q_DECL_IMPORT
#endif
#else
#define Q_DEMONRENDER_EXPORT
#endif

QT_END_NAMESPACE

#endif // QTDEMONRENDERGLOBAL_H
